name: main
on: [push, pull_request]
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:focal
    steps:
    - uses: actions/checkout@v2
    - run: |
        sudo apt-get -qq update
        sudo apt-get -qq install software-properties-common
        sudo add-apt-repository -y ppa:qpid/released
        sudo apt-get -qq update
        sudo apt-get -qq install build-essential make openjdk-11-jdk maven nodejs python3 python3-numpy unzip xz-utils
        sudo apt-get -y install libqpid-proton-cpp12-dev python3-qpid-proton libsasl2-2 libsasl2-dev libsasl2-modules sasl2-bin
    - run: make test
