name: main
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: apt-get -qq update
    - run: apt-get -qq install software-properties-common
    - run: add-apt-repository -y ppa:qpid/released
    - run: apt-get -qq update
    - run: apt-get -qq install build-essential make openjdk-11-jdk maven nodejs python3 python3-numpy unzip xz-utils
    - run: apt-get -y install libqpid-proton-cpp12-dev python3-qpid-proton
    - run: libsasl2-2 libsasl2-dev libsasl2-modules sasl2-bin
    - run: make test
