name: main
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 1 * *"
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: "17"
        cache: "maven"
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - run: |
        sudo apt-get -qq update
        sudo apt-get -qq install software-properties-common
        sudo add-apt-repository -y ppa:qpid/released
        sudo apt-get -qq update
        sudo apt-get -qq install build-essential curl make nodejs npm python3 python3-numpy unzip zstd
        sudo apt-get -y install libqpid-proton-cpp12-dev python3-qpid-proton libsasl2-2 libsasl2-dev libsasl2-modules qdrouterd sasl2-bin
        sudo npm -g install rhea
    - run: sudo make install PREFIX=/usr
    - run: quiver-self-test
      env:
        NODE_PATH: /usr/local/lib/node_modules
